// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import DisableSaveController from "./disable_save_controller"
application.register("disable-save", DisableSaveController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import LengthController from "./length_controller"
application.register("length", LengthController)
